feat(nixos): adjust config to work with nix

diff --git a/home/dot_config/zsh/completions.zsh.tmpl b/home/dot_config/zsh/completions.zsh.tmpl
--- a/home/dot_config/zsh/completions.zsh.tmpl
+++ b/home/dot_config/zsh/completions.zsh.tmpl
@@ -25,12 +25,16 @@ zstyle ':completion:*' menu select
 # enable privileged autocompletion (sudo)
 zstyle ':completion::complete:*' gain-privileges 1
 
+{{ if eq .osid "linux-nixos" }}
+source $(ls /nix/store/*zsh-syntax-highlighting*/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh) || echo "zsh-syntax-highlightning not found!"
+source $(ls /nix/store/*zsh-autosuggestions*/share/zsh-autosuggestions/zsh-autosuggestions.zsh) || echo "zsh-autosuggestions not found"
+{{ else }}
 if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
   source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
-elif [[ -z $IN_NIX_SHELL ]]; then
-  echo "zsh-syntax-highlightning not found"
+elif [[ -z $IN_NIX_SHELL && $OS != "linux-nixos" ]]; then
+  echo "zsh-syntax-highlightning not found $OS"
 else
-  source $(ls $NIX_STORE/*zsh-syntax-highlighting*/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh) || echo "zsh-syntax-highlightning not found"
+  source $(ls $NIX_STORE/*zsh-syntax-highlighting*/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh) || echo "zsh-syntax-highlightning not found!"
 fi
 
 if [[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
@@ -40,3 +44,4 @@ elif [[ -z $IN_NIX_SHELL ]]; then
 else
   source $(ls $NIX_STORE/*zsh-autosuggestions*/share/zsh-autosuggestions/zsh-autosuggestions.zsh) || echo "zsh-autosuggestions not found"
 fi
+{{ end }}
diff --git a/home/dot_config/zsh/prompt.zsh.tmpl b/home/dot_config/zsh/prompt.zsh.tmpl
--- a/home/dot_config/zsh/prompt.zsh.tmpl
+++ b/home/dot_config/zsh/prompt.zsh.tmpl
@@ -1,3 +1,6 @@
+{{ if eq .osid "linux-nixos" }}
+source $(ls /nix/store/*spaceship-prompt*/lib/spaceship-prompt/spaceship.zsh) || echo "❌ spaceship-prompt not found"
+{{ else }}
 if [[ -f /usr/lib/spaceship-prompt/spaceship.zsh ]]; then
   source /usr/lib/spaceship-prompt/spaceship.zsh
 elif [[ -z $IN_NIX_SHELL ]]; then
@@ -5,6 +8,7 @@ elif [[ -z $IN_NIX_SHELL ]]; then
 else
   source $(ls $NIX_STORE/*spaceship-prompt*/lib/spaceship-prompt/spaceship.zsh) || echo "❌ spaceship-prompt not found"
 fi
+{{ end }}
 
 # ORDER
 SPACESHIP_PROMPT_ORDER=(
